conf/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('core_app.urls')),
    path('jira/', include('jira_app.urls')),
    path('sonar/', include('sonarqube_app.urls')),
    path('resources/', include('resources_app.urls')),
    path('', include('google_api.urls')),
]

sonarqube_app/urls.py
from django.urls import path
from .views import SonarPageView, SonarFilterPageView

urlpatterns = [
    path('',  SonarPageView.as_view(), name='sonar'),
    path('filtersonar/',  SonarFilterPageView.as_view(), name='filtersonar'),
]

sonarqube_app/forms.py
from django import forms
from .utils.const import URL_GOOGLE_DRIVE


class SonarForm(forms.Form):
    url = forms.URLField(max_length=250, required=True,
                         initial=URL_GOOGLE_DRIVE)


class SonarFormInput(forms.Form):
    from_date = forms.DateField(required=True,)
    to_date = forms.DateField(required=True,)
    unit_test = forms.IntegerField(max_value=100, min_value=0, required=False)
    blocker = forms.IntegerField(required=False)
    critical = forms.IntegerField(required=False)
    major = forms.IntegerField(required=False)
    minor = forms.IntegerField(required=False)
    show_chart = forms.BooleanField(initial=True)

    def __init__(self, projects, *args, **kwargs):
        super(SonarFormInput, self).__init__(*args, **kwargs)
        self.fields['project'] = forms.CharField(
            widget=forms.Select(choices=projects))

sonarqube_app/views.py
from django.views.generic.base import TemplateView
from django.urls import reverse
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse


import json

from google_api.sheets_api import GoogleAPI

from .utils.cell import Cell
from .utils.const import URL_GOOGLE_DRIVE, EXPECT_HEADER, PROJECT_SHEET, CONFIG_SHEET, SONARQUBE_PAGE
from .forms import SonarForm, SonarFormInput


class SonarPageView(TemplateView):

    template_name = SONARQUBE_PAGE

    def __init__(self):
        self.context = {'title': 'Sonar', 'card_title': 'Sonar Report'}

    def post(self, request):
        """[Function will run when click button search in Sonar Report page]

        Arguments:
            request {[wsgi]}

        Returns:
            [route] -- [Authorize page if user not login or Input Sonar page]
        """
        drive_url = request.POST['url']
        inital_data = {'url': drive_url}

        # check url input
        if not drive_url.startswith('https://docs.google.com/spreadsheets/d/'):
            self.context.update({
                'status': 'Invalid Google Sheet URL.',
                'form': SonarForm(initial=inital_data)
            })
            return render(request, SONARQUBE_PAGE, self.context)

        # update parameters to session
        request.session.update({
            'from_post': True,
            'redirect_url': 'sonar',
            'drive_id': drive_url.split('/')[5],
            'initial': inital_data
        })
        if 'credentials' not in request.session:
            return redirect(reverse('authorize'))
        return redirect(reverse('sonar'))

    def get(self, request):
        """[Function will return filter page]

        Arguments:
            request {[wsgi]}

        Returns:
            [html] -- Sonarqube page
        """
        self.context['form'] = SonarForm()
        filter_sonar = 'False'
        if set(['from_post', 'credentials']).issubset(list(request.session.keys())):
            request.session['from_post'] = False
            if request.session.get('initial', False):
                setattr(self.context['form'], 'initial',
                        request.session['initial'])
            
            google_api = GoogleAPI(request.session['credentials'])
            sheet = google_api.call_the_sheets_api()
            
            # Load data from sheet
            status_code, values = google_api.get_data(
                sheetsrange=PROJECT_SHEET, sheet=sheet, spreadsheetId=request.session['drive_id'])
                
            # render data to input form
            if status_code == 200 and values.get('values', False):
                projects = values.get('values', False)
                cell = Cell(projects)
                # check value columns in google sheets
                mess = cell.check_header_cell(EXPECT_HEADER)
                self.context['status'] = mess
                list_project, mess = cell.get_project_list()
                self.context['status'] = mess
                if list_project:
                    input_form = SonarFormInput(list_project)
                    self.context['input_from'] = input_form
                    filter_sonar = 'True'
            else:
                if status_code != 200:
                    self.context['status'] = values
                    if status_code == 403:
                        self.context['status'] = values + \
                            '. Please click <a href="/authorize">here</a> to change account'
                else:
                    self.context['status'] = 'Not found data Projects in Google Sheets file'

            # get data config
            status_code, values = google_api.get_data(
                sheetsrange=CONFIG_SHEET, sheet=sheet, spreadsheetId=request.session['drive_id'])

            if status_code == 200 and values.get('values', False):
                configs = values.get('values', False)
                cell = Cell(config=configs)
                dict_config, mess_config = cell.get_config()
                if len(mess_config):
                    self.context['status'] = mess_config
                if dict_config and self.context.get('input_from', False):
                    setattr(self.context['input_from'], 'initial', dict_config)
                    filter_sonar = 'True'
            else:
                if status_code != 200:
                    self.context['status'] = values
                    if status_code == 403:
                        self.context['status'] = values + \
                            '. Please click <a href="/authorize">here</a> to change account'
                else:
                    self.context['status'] = 'Not found data config in Google Sheets file'
        self.context['filter_sonar'] = filter_sonar
        return render(request, SONARQUBE_PAGE, self.context)


class SonarFilterPageView(TemplateView):

    template_name = SONARQUBE_PAGE

    def post(self, request):
        print(1111111111111111)
        return JsonResponse({'summary': json.dumps({'message': 'aaaaaa'})})

sonarqube_app/templates/sonar_filter.html
{% load widget_tweaks %}

<hr style="border-top: 1px dashed;">
<div class="d-flex align-items-center mb-3 row">
    <div class="col-sm-2 text-right">
        Project<span class="text-danger">*</span>:
    </div>
    {{ input_from.project | append_attr:"multiple" | add_class:"col-sm-3 px-0 form-control" }}
    <div class="col-sm-1 ml-4 text-right">From<span class="text-danger">*</span>:</div>
    <div class="input-group date flex-nowrap col-sm-2 px-0 datetime-picker" id="datetimepickerfrom"
        data-target-input="nearest">
        {{ input_from.from_date | add_class:"col-sm-10 text-center datetimepicker-input form-control" | append_attr:"data-target:#datetimepickerfrom" }}
        <div class="input-group-append" data-target="#datetimepickerfrom" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar-alt"></i></div>
        </div>
    </div>
    <div class="col-sm-1 text-right">To<span class="text-danger">*</span>:</div>
    <div class="input-group date flex-nowrap col-sm-2 px-0 datetime-picker" id="datetimepickerto"
        data-target-input="nearest">
        {{ input_from.to_date | add_class:"col-sm-10 text-center datetimepicker-input form-control" | append_attr:"data-target:#datetimepickerto"}}
        <div class="input-group-append " data-target="#datetimepickerto" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar-alt"></i></div>
        </div>
    </div>
</div>
<div class="d-flex align-items-center mb-3 text-center row">
    <div class="col-sm-2 text-right">
        Blocker:
    </div>
    {{ input_from.blocker | add_class:"col-sm-1 text-center input-validation form-control" }}
    <div class="col-sm-1 text-right">
        Critical:
    </div>
    {{ input_from.critical | add_class:"col-sm-1 text-center input-validation form-control"}}
    <div class="col-sm-1 ml-4 text-right">
        Major:
    </div>
    {{ input_from.major | add_class:"col-sm-1 text-center input-validation form-control"}}
    <div class="col-sm-2 text-right">
        Minor:
    </div>
    {{ input_from.minor | add_class:"col-sm-1 text-center input-validation form-control"}}
</div>
<div class="d-flex align-items-center mb-3 text-center row">
    <div class="col-sm-2 text-right">
        Unit Test(%):
    </div>
    {{ input_from.unit_test | add_class:"col-sm-1 text-center input-validation form-control" }}
</div>
<div class="d-flex align-items-center mb-3 justify-content-center">
    <button type="submit" class="btn btn-primary" name="view">View</button>
</div>
<div class="d-flex align-items-center mb-3 justify-content-end">
    {{ input_from.show_chart }}
    <label for="id_show_chart">Show Charts</label>
</div>

sonarqube_app/templates/sonar_page.html
{% extends "card.html" %}

{% load static %}
{% load widget_tweaks %}

{% block partial_settings %}
{% block scripts %}
<link rel="stylesheet" type="text/css" href="{% static 'sonarqube_app/css/styles.css' %}">
<script type="text/javascript" charset="utf8" src="{% static '/sonarqube_app/js/static.js' %}"></script>
{% endblock %}


<div class="container">
    <form method="POST" action="{% url 'sonar'%}" id="form_submit">
        {% csrf_token %}
        <div class="d-flex align-items-center row">
            <div class="col-sm-2 text-right">
                Google File<span class="text-danger">*</span>:
            </div>
            <div class="col-sm-8 pl-0">
                {{ form.url | add_class:"form-control"}}
            </div>

            <div class="col-2">
                <button type="submit" class="btn btn-primary-outline p-0">
                    <li class="fa fa-search" style="font-size: 30px"></li>
                </button>
            </div>
        </div>
        <p class='error-message offset-sm-2' mess="{{status}}">
            {{status}}
        </p>
        {% if filter_sonar == 'True' %}
        {% include "sonar_filter.html" %}
        {% endif %}
    </form>
</div>

{% endblock %}